### PR TITLE
Test rename 3

### PR DESCRIPTION
**Pull request by MartinBasti**
This change is [Reviewable](https://reviewable.io/reviews/bastiak/ipa-devel-tools/15)

### CODE REVIEW

**Comment by MartinBasti** [comment]
test

**Comment by MartinBasti** [comment]
```
aug 22 17:01:05 dhcp129-96.brq.redhat.com /usr/bin/fedmsg-hub[14648]: [testgithubconsumer ERROR]: Failed with: global name 'pul_req' is not defined
                                                                      Traceback (most recent call last):
                                                                        File "build/bdist.linux-x86_64/egg/githubconsumer/githubconsumer.py", line 363, in consume
                                                                          method(msg)
                                                                        File "build/bdist.linux-x86_64/egg/githubconsumer/githubconsumer.py", line 322, in pr_reopened
                                                                          return self._pr_handler(gh_msg)
                                                                        File "build/bdist.linux-x86_64/egg/githubconsumer/githubconsumer.py", line 274, in _pr_handler
                                                                          return self.formatter.fmt_pr(msg)
                                                                        File "build/bdist.linux-x86_64/egg/githubconsumer/githubconsumer.py", line 165, in fmt_pr
                                                                          body = super(EmailFormatter, self).fmt_pr(comment)
                                                                        File "build/bdist.linux-x86_64/egg/githubconsumer/githubconsumer.py", line 63, in fmt_pr
                                                                          project=self.project, **pul_req
                                                                      NameError: global name 'pul_req' is not defined

```

**Comment by MartinBasti** [comment]
test

**Comment by MartinBasti** [comment]
test

**Comment by ghost** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/bastiak/ipa-devel-tools/15)_

**Comment by MartinBasti** [comment]
test

**Comment by MartinBasti** [comment]
q

**Pull request closed without merging**
